# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
server:
  port: 8083

spring:
  application:
    name: CART-SERVICE
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/cart_db
    username: Chandan
    password: Chandan@23
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Redis Configuration (For Caching User Carts)
  data:
    redis:
      host: localhost
      port: 6379

  # Kafka Configuration (For Listening to Product Deletions)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cart-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# API Documentation
# API Documentation
springdoc:
  api-docs:
    enabled: true
    # This aligns with the path the Gateway is looking for
    path: /cart/v3/api-docs 
  swagger-ui:
    path: /swagger-ui.html
  # This ensures relative paths inside Swagger are correct
  server:
    url: /cart