server:
  port: 8082

spring:
  application:
    name: PRODUCT-SERVICE
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: Chandan
    password: Chandan@23
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Redis Configuration (For Caching Product Details)
  data:
    redis:
      host: localhost
      port: 6379

  # Kafka Configuration (For Sending Product Events)
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Key and Value must be serialized to bytes for Kafka
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# API Documentation
springdoc:
  api-docs:
    enabled: true
    path: /product/v3/api-docs 
  swagger-ui:
    path: /swagger-ui.html
  server:
    url: /product